basePath: /v1
definitions:
  entity.User:
    properties:
      email:
        example: test@test.com
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Andrey
        type: string
      phone:
        example: "+79999999999"
        type: string
    type: object
  v1.indexResponse:
    properties:
      users:
        items:
          $ref: '#/definitions/entity.User'
        type: array
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
  v1.userResponse:
    properties:
      email:
        example: test@test.com
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Andrey
        type: string
      phone:
        example: "+79999999999"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: User CRUD
  title: V1 API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Show all users
      operationId: index
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.indexResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Show users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create new user
      operationId: create
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.userResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Create new user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update exists user
      operationId: update
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.userResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Update user
      tags:
      - users
  /users/:id:
    delete:
      consumes:
      - application/json
      description: Delete user from db
      operationId: delete
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Delete user by id
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Show user detail
      operationId: show
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.userResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Show user by id
      tags:
      - users
swagger: "2.0"
